name: Test
on:
    push:
        branches:
            - "*"

jobs:
    test:
        name: Unit tests

        strategy:
            matrix:
                go-version: [1.16.x, 1.17.x]
                os: [ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Go
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Test
              run: |
                  go version
                  go vet ./...
                  go test ./...
